# Generated by Django 5.2.6 on 2025-10-30 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Имя')),
                ('surname', models.CharField(max_length=80, verbose_name='Фамилия')),
                ('status', models.CharField(choices=[('max_active', 'Ищу работу'), ('active', 'Рассматриваю предложения'), ('non_active', 'Не ищу работу')], default='max_active', max_length=26)),
                ('salary', models.IntegerField(default=0)),
                ('grade', models.CharField(choices=[('intern', 'Стажер'), ('Junior', 'Джуниор'), ('middle', 'Миддл'), ('senior', 'Синьор'), ('lid', 'Лид')], default='middle', max_length=20)),
                ('education', models.TextField(blank=True, default='4 класса начальной школы.', verbose_name='Образование')),
                ('experience', models.TextField(blank=True, default='Яндекс...  доставка', verbose_name='Опыт работы')),
                ('portfolio', models.URLField(blank=True, max_length=120, verbose_name='Портфолио')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='main.specialty', to_field='code', verbose_name='Специализация')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='my_resume', to=settings.AUTH_USER_MODEL, verbose_name='Резюме')),
            ],
        ),
    ]
