# Generated by Django 5.2.6 on 2025-10-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_resume'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'verbose_name': 'Резюме', 'verbose_name_plural': 'Резюме'},
        ),
        migrations.AlterField(
            model_name='resume',
            name='grade',
            field=models.CharField(choices=[('intern', 'Стажер'), ('Junior', 'Джуниор'), ('middle', 'Миддл'), ('senior', 'Синьор'), ('lid', 'Лид')], default='middle', max_length=20, verbose_name='Квалификация'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='salary',
            field=models.IntegerField(default=1, verbose_name='Вознаграждение'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[('max_active', 'Ищу работу'), ('active', 'Рассматриваю предложения'), ('non_active', 'Не ищу работу')], default='max_active', max_length=26, verbose_name='Готовность к работе'),
        ),
    ]
