# Generated by Django 5.2.6 on 2025-09-16 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('logo', models.URLField(blank=True, default='https://place-hold.it/100x60')),
                ('description', models.TextField(blank=True)),
                ('employee_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Компании',
                'verbose_name_plural': 'Компании',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(max_length=30)),
                ('picture', models.URLField(blank=True, default='https://place-hold.it/100x60')),
            ],
            options={
                'verbose_name': 'Специализации',
                'verbose_name_plural': 'Специализации',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('skills', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('salary_min', models.IntegerField(blank=True, default=0)),
                ('salary_max', models.IntegerField(blank=True, default=0)),
                ('published_at', models.DateField(auto_now_add=True)),
                ('company', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='vacancies',
                    to='main_page_app.company')),
                ('specialty', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='vacancies',
                    to='main_page_app.specialty', to_field='code')),
            ],
            options={
                'verbose_name': 'Вакансии',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['id'],
            },
        ),
    ]
