# Generated by Django 5.2.6 on 2025-10-24 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page_app', '0003_company_owner_alter_company_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='company',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='specialty',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Specialty',
        ),
        migrations.DeleteModel(
            name='Vacancy',
        ),
    ]
