# Generated by Django 5.2.6 on 2025-10-24 21:08

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Код')),
                ('title', models.CharField(max_length=30, verbose_name='Направление')),
                ('picture', models.ImageField(blank=True, default='https://place-hold.it/100x60', upload_to='specialties', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Специализацию',
                'verbose_name_plural': 'Специализации',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('location', models.CharField(max_length=50, verbose_name='Город')),
                ('logo', models.ImageField(blank=True, default='https://place-hold.it/100x60', upload_to='companies', verbose_name='Логотип')),
                ('description', models.TextField(blank=True, verbose_name='Инф. о компании')),
                ('employee_count', models.IntegerField(default=0, verbose_name='Кол-во сотрудников')),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Компанию',
                'verbose_name_plural': 'Компании',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('skills', models.TextField(blank=True, verbose_name='Навыки')),
                ('description', models.TextField(blank=True, verbose_name='Текст')),
                ('salary_min', models.IntegerField(blank=True, default=0, verbose_name='Зарплата от')),
                ('salary_max', models.IntegerField(blank=True, default=0, verbose_name='Зарплата до')),
                ('published_at', models.DateField(auto_now_add=True, verbose_name='Опубликовано')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='user_company.company', verbose_name='Компания')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='user_company.specialty', to_field='code', verbose_name='Специализация')),
            ],
            options={
                'verbose_name': 'Вакансию',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('written_username', models.CharField(max_length=80, verbose_name='Имя')),
                ('written_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', verbose_name='Телефон')),
                ('written_cover_letter', models.TextField(verbose_name='Сопроводительное письмо')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='user_company.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Отклик',
                'verbose_name_plural': 'Отклики',
            },
        ),
    ]
