# Generated by Django 5.2.6 on 2025-10-28 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_company', '0002_alter_company_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
